# Generated by Django 3.1 on 2020-08-26 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snack',
            name='description',
            field=models.CharField(default='Enter Description', max_length=200),
        ),
    ]
