# Generated by Django 3.1 on 2020-08-26 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0002_snack_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='snack',
            name='rank',
            field=models.IntegerField(default=1),
        ),
    ]
